sudo: true
language: ruby
addons:
  code_climate:
    repo_token: d15d5e64664e88abc10a87df26fa6b6e4c8822fcab4fbafc326f8032b1aeb75a
rvm:
- 2.3
- 2.4
- ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
- gem install bundle
install:
- bundle install
script:
- bundle exec rspec
